# Generated by Django 5.2.15 on 2026-06-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyEntry",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("photo_path", models.CharField(max_length=255)),
                ("word_target", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("picked", "picked"), ("submitted", "submitted")],
                        default="picked",
                        max_length=12,
                    ),
                ),
                ("effective_word_count", models.PositiveIntegerField(null=True)),
                ("performance_pct", models.FloatField(null=True)),
                ("revealed_tiles", models.JSONField(null=True)),
                ("picked_at", models.DateTimeField()),
                ("submitted_at", models.DateTimeField(null=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
