/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config */
        get: operations["diary_api_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Today */
        get: operations["diary_api_today"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pick */
        post: operations["diary_api_pick"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit */
        post: operations["diary_api_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gallery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gallery */
        get: operations["diary_api_gallery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["diary_api_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dev Login */
        post: operations["diary_api_dev_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/advance-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dev Advance Day
         * @description Shift the in-memory dev clock forward one day (testing the daily loop).
         */
        post: operations["diary_api_dev_advance_day"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dev Reset
         * @description Wipe all entries and return the dev clock to today — a clean slate.
         */
        post: operations["diary_api_dev_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConfigOut */
        ConfigOut: {
            /** Devlogin */
            devLogin: boolean;
        };
        /** FrozenEntryOut */
        FrozenEntryOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Tier */
            tier: string;
            /** Name */
            name: string;
            /** Wordtarget */
            wordTarget: number;
            /** Effectivewordcount */
            effectiveWordCount: number;
            /** Performancepct */
            performancePct: number;
            /** Photourl */
            photoUrl: string;
            /** Revealedtiles */
            revealedTiles: number[];
        };
        /** OfferSlotOut */
        OfferSlotOut: {
            /** Tier */
            tier: string;
            /** Name */
            name: string;
            /** Wordtarget */
            wordTarget: number;
            /** Photourl */
            photoUrl: string;
            /** Seedtile */
            seedTile: number;
        };
        /** PickedOut */
        PickedOut: {
            /** Photopath */
            photoPath: string;
            /** Photourl */
            photoUrl: string;
            /** Tier */
            tier: string;
            /** Name */
            name: string;
            /** Wordtarget */
            wordTarget: number;
            /** Seedtile */
            seedTile: number;
        };
        /** TodayOut */
        TodayOut: {
            /**
             * Today
             * Format: date
             */
            today: string;
            /** State */
            state: string;
            /** Offer */
            offer?: (components["schemas"]["OfferSlotOut"] | null)[] | null;
            picked?: components["schemas"]["PickedOut"] | null;
            submitted?: components["schemas"]["FrozenEntryOut"] | null;
        };
        /** PickIn */
        PickIn: {
            /** Tier */
            tier: string;
        };
        /** SubmitIn */
        SubmitIn: {
            /** Text */
            text: string;
        };
        /** GalleryOut */
        GalleryOut: {
            /** Items */
            items: components["schemas"]["FrozenEntryOut"][];
            /** Photoscollected */
            photosCollected: number;
            /** Pooltotal */
            poolTotal: number;
        };
        /** CalendarDayOut */
        CalendarDayOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Performancepct */
            performancePct: number;
        };
        /** StatsOut */
        StatsOut: {
            /**
             * Today
             * Format: date
             */
            today: string;
            /** Currentstreak */
            currentStreak: number;
            /** Longeststreak */
            longestStreak: number;
            /** Totalwords */
            totalWords: number;
            /** Daysdelivered */
            daysDelivered: number;
            /** Photoscollected */
            photosCollected: number;
            /** Poolunlockedpct */
            poolUnlockedPct: number;
            /** Year */
            year: number;
            /** Month */
            month: number;
            /** Daysinmonth */
            daysInMonth: number;
            /** Firstweekday */
            firstWeekday: number;
            /** Calendar */
            calendar: components["schemas"]["CalendarDayOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    diary_api_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
        };
    };
    diary_api_today: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayOut"];
                };
            };
        };
    };
    diary_api_pick: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PickIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickedOut"];
                };
            };
        };
    };
    diary_api_submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrozenEntryOut"];
                };
            };
        };
    };
    diary_api_gallery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GalleryOut"];
                };
            };
        };
    };
    diary_api_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
        };
    };
    diary_api_dev_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    diary_api_dev_advance_day: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    diary_api_dev_reset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
